SELECT 	T1.NM_AUTOR,
		COUNT(T3.ID_LIVRO) AS "QT_LIVRO"
FROM AUTOR AS T1
LEFT JOIN AUTORIA AS T2 ON T1.ID_AUTOR = T2.ID_AUTOR
LEFT JOIN LIVRO AS T3 ON T2.ID_LIVRO = T3.ID_LIVRO
LEFT JOIN ASSUNTO AS T4 T3.ID_ASSUNTO = T4.ID_ASSUNTO
WHERE 	UPPER(T1.NM_AUTOR) LIKE "C%" AND
		UPPER(T3.NM_ASSUNTO) = "LITERATURA ESTRANGEIRA"
GROUP BY T1.NM_AUTOR
ORDER BY T1.NM_AUTOR ASC;

